### ISSUE TITLE
shog with lograge

### ISSUE THREAD

**Issue by casertap** [phallguy/shog#4]
Hi, your plugin is great thank you for that.
I would like to have a special formatting using lograge and some coloration with shog.

in my application.rb

```
  config.lograge.enabled = true
  config.lograge.formatter = Lograge::Formatters::Logstash.new
  config.lograge.custom_options = lambda do |event|
    unwanted_keys = %w[format action controller]
    params = event.payload[:params].reject { |key,_| unwanted_keys.include? key }
    # capture some specific timing values you are interested in
    {:params => params }
  end

```

in the initializers/shog.rb I have the default init and no colorization is done on my logs.
If I comment the lograge config, than the code is colorized.
Thanks.

**Comment by phallguy** [comment]
This may be related to #3. Will you try using that branch to see if it's able to properly inject itself alongside lograge?

I don't actually use lograge so diagnosing the root cause is going to be a bit challenging. If the referenced PR doesn't fix it for you, will you create a basic rails app with both lograge and shog configured and share that repo?
